# Generated by Django 6.0.3 on 2026-04-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
