[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/app/logs/nginx.log
stderr_logfile=/app/logs/nginx-error.log

[program:gunicorn]
command=gunicorn config.wsgi:application --bind 127.0.0.1:8000
directory=/app
autostart=true
autorestart=true
priority=20
redirect_stderr=true
stdout_logfile=/app/logs/gunicorn.log

[program:celery]
command=celery -A config worker --loglevel=info --pool=solo
directory=/app
autostart=true
autorestart=true
priority=30
redirect_stderr=true
stdout_logfile=/app/logs/celery.log

[program:celery-beat]
command=celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/app
autostart=true
autorestart=true
priority=40
redirect_stderr=true
stdout_logfile=/app/logs/celery-beat.log