# Generated by Django 6.0.3 on 2026-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["id"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="last_notification_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время последнего уведомления"
            ),
        ),
    ]
